language: scala
scala:
- 2.11.5
before_deploy:
- sbt package
- mv target/scala-2.11/marathon-env-plugin_*.jar marathon-env-plugin.jar
deploy:
  provider: releases
  api_key:
    secure: Deoy8MTbGF61ul46bsGwOvMoLv/xNSmK0ZnWEzQxp+BVmEfzlyxwuXlKl74OFJsE4wL+stNRggNZuubw/hKwTJ2xTLkz2jr9Y0tfgSoObb/Y3EwGN7Mwm5PJh/AJiGgPouqa1whjhrYV/0G4s5B/QbO5dFIoPXMrVeiXovRUmoqOuHVp7V1lLMmH2IXs3CGjA5ZePfbAq6qMEA3myg5FwERxE/x0491+eIAbIqY+TgfSKblSdl1qXUn3mJGRiw33rnzuLSPIBCBKDCjoYC3wh/dJW07DxCjo8hqjt9k4w9to82geA5xmC3PVjWHl5asRKZmNo5I9vv6KUe2Q8DttNQ8xi8056V/XQ+rHkFQ4i5B7gxCnk47SRNoikNFeMIYyUsspjIGiS9pXsPsmbILEZGntflJ169KkjRgpqjtmtHiItdsVDc9JlrLY5RQLo/Ol/btumQAFSCdJJX9heyb7Ev9suR9SjiQR96FNrTlhEm8SY5pXygm0pgON4Cu0kJCg6mg4dquykpP5VXq41Aldd3lg563lGcB32M2xpU3l5N3vGwkmRvz6Jg30B5doMDfoZov0bQUldCnDhymAkY0HZQvFsbXHQlTMy61eJ0w5+ZVa6IVGYycrdL13qNiFiD7kpHpEDCQAM3cLWpEZ7PDi6sf7v9Zw/irVGXgRNH9LSzI=
  file: marathon-env-plugin.jar
  skip_cleanup: true
  on:
    repo: criteo/marathon-env-plugin
    tags: true
    branche: master

